from . import hotel_room_block_wizard
from . import minibar_charge_wizard
from . import hotel_split_line_wizard
from . import hotel_role_assignment_wizard
from . import hotel_guest_request_submit_wizard
from . import registration_card_sign_print_wizard
from . import tax_invoice_sign_print_wizard
from . import commercial_invoice_sign_print_wizard
from . import reservation_document_print_wizard
