from datetime import datetime, time

from odoo import fields, models, _


class HotelRoomBlockWizard(models.TransientModel):
    _name = 'hotel.room.block.wizard'
    _description = 'Room Maintenance Block Wizard'

    room_id = fields.Many2one('hotel.room', string='Room', required=True)
    date_start = fields.Date(string='Block Start Date', default=fields.Date.context_today, required=True)
    date_end = fields.Date(string='Expected Vacant Date', required=True)
    reason = fields.Char(string='Reason for Block', required=True, help="e.g., Broken AC, Deep Cleaning")
    need_maintenance = fields.Boolean(
        string="Alert Maintenance Team?",
        default=False,
        help="Turn this on to automatically create a Maintenance Ticket.",
    )

    def action_confirm_block(self):
        for wizard in self:
            wizard.room_id.with_context(hotel_room_security_bypass=True).write({
                'availability_status': 'out_of_order',
            })

            maintenance_note = ""
            if wizard.need_maintenance and 'maintenance.request' in self.env:
                duration_days = max((wizard.date_end - wizard.date_start).days, 1)
                self.env['maintenance.request'].create({
                    'name': f"Room {wizard.room_id.name}: {wizard.reason}",
                    'description': (
                        f"Block Dates: {wizard.date_start} to {wizard.date_end}\n"
                        "This ticket was automatically generated by Housekeeping."
                    ),
                    'room_id': wizard.room_id.id,
                    'schedule_date': datetime.combine(wizard.date_start, time.min),
                    'duration': duration_days * 24.0,
                })
                maintenance_note = "<br/><br/><b>A maintenance ticket has been sent to the Maintenance Team.</b>"
            else:
                self.env['hotel.room.block'].sudo().create({
                    'name': _("OOO: %s") % wizard.room_id.name,
                    'room_id': wizard.room_id.id,
                    'date_from': wizard.date_start,
                    'date_to': wizard.date_end,
                    'state': 'active',
                    'source': 'manual',
                    'reason': wizard.reason,
                })

            wizard.room_id.message_post(body=f"""
                <div class="alert alert-warning" role="alert">
                    <b>Room Blocked</b><br/>
                    <b>Reason:</b> {wizard.reason}<br/>
                    <b>Blocked Until:</b> {wizard.date_end}
                    {maintenance_note}
                </div>
            """)
            wizard.room_id._reconcile_operational_status()
            wizard.room_id._sync_housekeeping_task_records()
