from odoo import models, fields, api, _

class HotelRoomBlockWizard(models.TransientModel):
    _name = 'hotel.room.block.wizard'
    _description = 'Room Maintenance Block Wizard'

    room_id = fields.Many2one('hotel.room', string='Room', required=True)
    date_start = fields.Date(string='Block Start Date', default=fields.Date.context_today, required=True)
    date_end = fields.Date(string='Expected Vacant Date', required=True)
    reason = fields.Char(string='Reason for Block', required=True, help="e.g., Broken AC, Deep Cleaning")
    
    # --- NEW FIELD: The Checkbox ---
    need_maintenance = fields.Boolean(string="Alert Maintenance Team?", default=False, 
                                      help="Turn this on to automatically create a Maintenance Ticket.")

    def action_confirm_block(self):
        """ 
        Updates the room status AND blocks the calendar to prevent overbooking.
        Optionally generates a Maintenance Ticket.
        """
        for wizard in self:
            # 1. Change the physical room status to blocked
            wizard.room_id.write({'state': 'blocked'})
            
            # 2. Find or create the dummy "Maintenance" guest
            maintenance_guest = self.env['res.partner'].search([('name', '=', 'Maintenance - OOO')], limit=1)
            if not maintenance_guest:
                maintenance_guest = self.env['res.partner'].create({'name': 'Maintenance - OOO'})

            # 3. Create the visual block on the Room Chart
            self.env['hotel.reservation'].create({
                'partner_id': maintenance_guest.id,
                'room_id': wizard.room_id.id,
                'room_type_id': wizard.room_id.room_type_id.id,
                'checkin_date': wizard.date_start,
                'checkout_date': wizard.date_end,
                'state': 'blocked', 
            })
            
            # --- NEW: AUTO-GENERATE MAINTENANCE TICKET ---
            maintenance_note = ""
            # The 'if in self.env' makes sure this doesn't crash if the Odoo Maintenance app isn't installed!
            if wizard.need_maintenance and 'maintenance.request' in self.env:
                self.env['maintenance.request'].create({
                    'name': f"Room {wizard.room_id.name}: {wizard.reason}",
                    'description': f"Block Dates: {wizard.date_start} to {wizard.date_end}\nThis ticket was automatically generated by Housekeeping.",
                    # If you have a specific priority field, you can set it here too!
                })
                # Add a note to the chatter message so staff know the ticket was created
                maintenance_note = "<br/><br/><b>🛠️ An official ticket has been sent to the Maintenance Team!</b>"
            # ---------------------------------------------

            # 4. Log the message in the Room's history
            msg = f"""
                <div class="alert alert-warning" role="alert">
                    <b>⚠️ Room Blocked</b><br/>
                    <b>Reason:</b> {wizard.reason}<br/>
                    <b>Blocked Until:</b> {wizard.date_end}
                    {maintenance_note}
                </div>
            """
            wizard.room_id.message_post(body=msg)